include common/ilib-cpp/ilib-cpp.mak
include lunch/lunch.mak
include sdk/common/lib-cpp/lib-cpp.mak
include sdk/common/linux/dns/dns.mak
include sdk/common/linux/file/file.mak
include sdk/common/linux/network/network.mak
include sdk/common/linux/os-cpp/os-cpp.mak
include sdk/common/linux/postgresql/postgresql.mak
include sdk/common/service/database_shared/database_shared.mak
include sdk/common/linux/process/process.mak
include sdk/common/linux/system/system.mak
include sdk/common/linux/tcp/tcp.mak
include sdk/common/linux/time/time.mak
include sdk/common/linux/timezone/timezone.mak
include sdk/common/linux/uds/uds.mak
include sdk/common/linux/valgrind/valgrind.mak
include sdk/common/service/http_client/http_client.mak
include sdk/common/service/openssl_shared/openssl_shared.mak
include sdk/common/service/random/random.mak
include sdk/common/service/smtp/smtp.mak
include sdk/common/service/tls/tls.mak
include sdk/common/service/webserver_shared/webserver_shared.mak
include sdk/common/service/webserverplugin/webserverplugin.mak
